PowerAssert.MultipleAssertions.PolyAssertException: PolyAssert encountered 3 failures:
> I will report all the errors i saw when i get disposed
============================================================
ERROR in EndToEndTest.PolyAssert at ...\EndToEndTest.cs:<line>:
============================================================
IsTrue failed, expression was:

x == 5
. __
. |
| False
6

============================================================

============================================================
ERROR in EndToEndTest.PolyAssert at ...\EndToEndTest.cs:<line>:
============================================================
IsTrue failed, expression was:

x == 7
. __
. |
| False
6

============================================================

============================================================
ERROR in EndToEndTest.PolyAssert at ...\EndToEndTest.cs:<line>:
============================================================
Wah wah
============================================================

> PolyAssert.Log messages are only printed if the test fails

   at PowerAssert.MultipleAssertions.PolyAssert.StopIfErrorsHaveOccurred() in ...\PolyAssert.cs
   at PowerAssert.MultipleAssertions.PolyAssert.Dispose() in ...\PolyAssert.cs
   at PowerAssertTests.Approvals.EndToEndTest.PolyAssert() in ...\EndToEndTest.cs